### ISSUE TITLE
No contents in Userprofile section

### ISSUE THREAD

**Issue by Ocrimops** [Bixie/pagekit-userprofile#10]
![2016-11-15 09_39_53-info _ project](https://cloud.githubusercontent.com/assets/1447928/20298691/9709fc62-ab17-11e6-9af6-3a2111366d16.png)

I use Pagekit v1.0.9 and installed the Bixie Framework and Userprofile. Navigating to the Userprofile section results in an empty content area. Do I miss anything?

![2016-11-15 09_41_08-userprofile _ project](https://cloud.githubusercontent.com/assets/1447928/20298738/e6d097d8-ab17-11e6-93a5-87f2e4d6fa5f.png)

**Comment by Ocrimops** [comment]
Accordingly I get this error:

fields.js?v=214f:1 Uncaught ReferenceError: Vue is not defined(…)
(anonymous function) @ fields.js?v=214f:1
t @ fields.js?v=214f:1
(anonymous function) @ fields.js?v=214f:1
(anonymous function) @ fields.js?v=214f:1

**Comment by doughnet** [comment]
same issue with me

idea when this will be resolved?

**Comment by Ocrimops** [comment]
... or when there will be a reply at least? ;)

**Comment by doughnet** [comment]
true ... maybe the project is dead now?

**Comment by malles** [comment]
Sorry for the late reply.
Please make sure you have the new Bixie Framework from the Marketplace installed. Delete the old framework.

**Comment by Ocrimops** [comment]
Thanks for the reply. Unfortunately it did not solve the problem. I always install from marketplace exclusively.
Nevertheless, I deleted the Bixie Framework and installed it again from marketplace. It again was v1.0.0
After the installation I could update it via Extension manager to v1.0.1
To make sure, that the Userprofile is up to date as well, I did the same with that Extension (delete and install)

Afterwards I cleared all caches.

![image](https://cloud.githubusercontent.com/assets/1447928/20760399/3d2f777a-b720-11e6-8e85-c6b5efdc3794.png)

Navigating to Userprofile I still get the error:

Uncaught ReferenceError: Vue is not defined
    at Object.<anonymous> (http://.../packages/bixie/userprofile/app/bundle/fields.js?v=214f:1:2027)
    at t (http://.../packages/bixie/userprofile/app/bundle/fields.js?v=214f:1:117)
    at http://.../packages/bixie/userprofile/app/bundle/fields.js?v=214f:1:204
    at http://.../packages/bixie/userprofile/app/bundle/fields.js?v=214f:1:209

Anything else to do?

**Comment by malles** [comment]
Please try updating to 1.3.0, I think this commit https://github.com/Bixie/pagekit-userprofile/commit/467258098a393ea31464441efc9d0f1d50e4f6ed has fixed that.

**Comment by Ocrimops** [comment]
Yeehaa, that solved the issue. Thanks a lot, nice work!
