### ISSUE TITLE
Feature restrict editable & restrict access

### ISSUE THREAD

**Issue by stefanpkc** [Bixie/pagekit-userprofile#3]
At this moment you can set who can fill in certain fields on their profile.

It could be useful to set also a permission for who can fill in the field in the backend (as a manager/admin). This way you can restrict editing by users themselve but set a user role who can edit the values. There could also be a permission who can view the value.

**Comment by malles** [comment]
I can see the idea of this, but it would complicate things enormously. I think this should be handled in a custom fieldtype.
