### ISSUE TITLE
I cant remove the Birthday Field

### ISSUE THREAD

**Issue by newgabo2006** [Bixie/pagekit-userprofile#7]
It is imposible t remove this field i already added

**Comment by CopyJosh** [comment]
Created a date of birth field and deleted it.. can you elaborate in any way?

**Comment by malles** [comment]
Make sure you select the field and then click the appearing trashcan to delete the field.
![image](https://cloud.githubusercontent.com/assets/5442402/17101112/f9b86586-5272-11e6-8f54-1180a317b78b.png)
