### ISSUE TITLE
Cyrillic encoding problem

### ISSUE THREAD

**Issue by denisbednov** [Bixie/pagekit-userprofile#8]
Hi!
When I'm using radio bullets field with options, which contains cyrillic symbols, then I'm getting wrong behavior.

This is list of my options:
![image](https://cloud.githubusercontent.com/assets/5417828/15775505/dd71692e-298a-11e6-8842-7ba762664cb7.png)

This is the problem:
![image](https://cloud.githubusercontent.com/assets/5417828/15775528/feb1f964-298a-11e6-9234-10756fcbad3c.png)

Thanks!

**Comment by malles** [comment]
You can unlink the label and the value from each other, thus creating 'html/database' safe values to work with in the radio-inputs and as keys.
![image](https://cloud.githubusercontent.com/assets/5442402/17101070/b50fe882-5272-11e6-8914-6f5233f73665.png)
