### ISSUE TITLE
Vue.js Bug: Error when evaluating expression

### ISSUE THREAD

**Issue by evgenious** [Bixie/pagekit-userprofile#9]
Wanted to try out the plugin and its not possible to save the fields. Always getting some vue.js errors and a really huge sql errorlog, that disappears after a few seconds...

`vue.js?v=180d:1023 [Vue warn]: Error when evaluating expression "form.email.invalid": TypeError: Cannot read property 'email' of undefined (found in component: <settings>)warn @ vue.js?v=180d:1023Watcher.get @ vue.js?v=180d:3180Watcher @ vue.js?v=180d:3162Directive._bind @ vue.js?v=180d:8342linkAndCapture @ vue.js?v=180d:6925compositeLinkFn @ vue.js?v=180d:6901Vue._compile @ vue.js?v=180d:8608Vue.$mount @ vue.js?v=180d:9443Vue._init @ vue.js?v=180d:2472VueComponent @ VM60877:2build @ vue.js?v=180d:5841mountComponent @ vue.js?v=180d:5758(anonymous function) @ vue.js?v=180d:5720(anonymous function) @ vue.js?v=180d:5738cb @ vue.js?v=180d:371Vue._resolveComponent @ vue.js?v=180d:8866resolveComponent @ vue.js?v=180d:5740setComponent @ vue.js?v=180d:5719update @ vue.js?v=180d:5693Directive._bind @ vue.js?v=180d:8357linkAndCapture @ vue.js?v=180d:6925compositeLinkFn @ vue.js?v=180d:6901Fragment @ vue.js?v=180d:3761FragmentFactory.create @ vue.js?v=180d:3978create @ vue.js?v=180d:4214diff @ vue.js?v=180d:4113update @ vue.js?v=180d:4046Directive._bind @ vue.js?v=180d:8357linkAndCapture @ vue.js?v=180d:6925compositeLinkFn @ vue.js?v=180d:6901Vue._compile @ vue.js?v=180d:8608Vue.$mount @ vue.js?v=180d:9443Vue._init @ vue.js?v=180d:2472Vue @ vue.js?v=180d:9507e @ vue.js?v=180d:1r @ vue.js?v=180d:1
vue.js?v=180d:22 POST http://127.0.0.1/pagekit/api/user/1 500 (Internal Server Error)`

Everything else, also other plugins work fine.

**Comment by evgenious** [comment]
Just found out this happens if you work with sqlite; With a fresh install on MySql the plugin works...

**Comment by malles** [comment]
This Vue warning is caused by the form-validator and is unpreventable at the moment. It is only a warning and can do no harm other than being annoying. It only shows when you have debug-mode on, it should be database independent.
